"""Curated failure-analysis knowledge base.

Mechanisms and signatures follow standard references (ASM Handbook Vol 11 Failure Analysis and
Prevention, Vol 12 Fractography) and are written here in our own words. ASTM/ASM standards are
cited by number as the authority for each confirming test (their text is copyrighted and is not
reproduced). Material entries are rough engineering ranges for screening, not design data.

Each failure-mode card carries:
  fractography = macro (camera-visible) vs micro (SEM-only) signatures
  astm         = the standard tests that confirm or characterise the mode
"""

# ---------------------------------------------------------------------------
# Failure modes
# ---------------------------------------------------------------------------
FAILURE_MODES = {
    "fatigue": {
        "name": "Fatigue",
        "summary": "Cracks initiate and grow under repeated (cyclic) loading at stresses below yield, then the part fails suddenly once the remaining section cannot carry the load.",
        "conditions": ["Cyclic or fluctuating load", "A stress concentration (notch, hole, weld toe, fillet)", "Often well below yield stress"],
        "evidence": ["Crack starts at a surface stress raiser", "Little or no gross deformation", "A flat crack-growth zone plus a rough final-overload zone"],
        "fractography": {"macro": "Beach marks / clamshell marks, ratchet marks where multiple origins meet, a flat fatigue zone and a coarse final fracture", "micro": "Striations (one per cycle) under SEM"},
        "astm": ["E466 force-controlled fatigue", "E647 fatigue crack-growth rate (da/dN)", "E606 strain-controlled fatigue"],
        "tests": ["SEM fractography for striations", "Locate the initiation site and its stress raiser", "Estimate the cyclic stress and compare with an S-N curve", "Check surface finish and residual stress"],
        "prevent": ["Remove stress concentrations, improve fillet radii", "Improve surface finish, shot peen for compressive residual stress", "Lower the cyclic stress range or add redundancy"],
    },
    "brittle_fracture": {
        "name": "Brittle fracture",
        "summary": "Sudden fracture with almost no plastic deformation, typically below the ductile-to-brittle transition temperature, at high strain rate, or from a sharp flaw in a low-toughness material.",
        "conditions": ["Low temperature (below the transition temperature)", "High strain rate or impact", "Pre-existing flaw or sharp notch", "Low-toughness material (many BCC steels, cast iron, high-strength steel)"],
        "evidence": ["No necking or thinning", "Fast, often single-event, failure", "Crack runs from a flaw or notch"],
        "fractography": {"macro": "Flat, bright surface, chevron marks pointing back to the origin", "micro": "Transgranular cleavage facets, or intergranular facets if grain boundaries are weak"},
        "astm": ["E23 Charpy V-notch impact (transition curve)", "E1820 fracture toughness (J, CTOD)", "E399 plane-strain fracture toughness (K_IC)"],
        "tests": ["Charpy impact across temperature to find the transition", "Fracture toughness", "Compare service temperature with the transition", "Find the initiating flaw"],
        "prevent": ["Use a tougher material or a lower transition temperature", "Keep service above the transition temperature", "Reduce thickness and sharp notches, control flaws"],
    },
    "ductile_overload": {
        "name": "Ductile overload",
        "summary": "A single load exceeded the strength of the part, which yielded and tore after visible plastic deformation.",
        "conditions": ["Single overload above yield then ultimate strength", "Often an unexpected or off-design load", "Undersized section or wrong material"],
        "evidence": ["Gross plastic deformation, necking or bending", "Failure traces to one overload event", "Shear lips at the edges"],
        "fractography": {"macro": "Dull, fibrous, often cup-and-cone surface with shear lips", "micro": "Microvoid coalescence (dimples) under SEM"},
        "astm": ["E8/E8M tension testing", "E18 / E384 hardness to confirm the strength level"],
        "tests": ["Confirm section size and actual loads", "Tensile test to confirm strength", "SEM for dimpled rupture", "Reconstruct the loading event"],
        "prevent": ["Increase section or use a stronger material", "Confirm real service loads and add margin", "Protect against off-design overloads"],
    },
    "general_corrosion": {
        "name": "General (uniform) corrosion",
        "summary": "Fairly even electrochemical loss of material across a surface in a corrosive environment, thinning the section over time.",
        "conditions": ["Corrosive environment (humid, marine, acidic, alkaline)", "Unprotected surface", "Long exposure"],
        "evidence": ["Uniform thinning and oxide/rust", "Predictable wall loss over time", "Roughened surface"],
        "fractography": {"macro": "General metal loss, scale, rust, no localised pits", "micro": "Not usually needed; uniform attack"},
        "astm": ["G31 immersion corrosion testing", "G1 cleaning and evaluating corrosion specimens"],
        "tests": ["Identify environment and corrosion product", "Measure wall loss and corrosion rate", "Check alloy vs environment compatibility"],
        "prevent": ["Select a compatible alloy, add coatings or inhibitors", "Control the environment", "Allow a corrosion thickness margin"],
    },
    "pitting_corrosion": {
        "name": "Pitting corrosion",
        "summary": "Localised attack that drills deep, narrow pits, usually where a passive film (stainless, aluminium) breaks down in chlorides, with little overall metal loss but high perforation risk.",
        "conditions": ["Passive alloy (stainless, aluminium) in chlorides", "Stagnant conditions", "Surface defects or deposits"],
        "evidence": ["Isolated deep pits, often under deposits", "Small weight loss but perforation", "Pits can initiate fatigue or SCC"],
        "fractography": {"macro": "Discrete pits, sometimes capped by corrosion product", "micro": "Crystallographic pit walls"},
        "astm": ["G48 ferric chloride pitting and crevice test", "G46 examination and evaluation of pitting", "G150 critical pitting temperature"],
        "tests": ["Map and measure pit depth", "Identify chlorides and deposits", "Pitting resistance (PREN) of the alloy"],
        "prevent": ["Use a higher-PREN alloy (more Mo)", "Remove chlorides and deposits, avoid stagnation", "Cathodic protection or coatings"],
    },
    "crevice_corrosion": {
        "name": "Crevice corrosion",
        "summary": "Intense localised attack inside shielded gaps (under gaskets, bolt heads, deposits) where stagnant chemistry becomes aggressive, common in passive alloys.",
        "conditions": ["A tight crevice or shielded area", "Passive alloy in chloride or stagnant fluid", "Gaskets, deposits, lap joints, threads"],
        "evidence": ["Attack concentrated at the crevice mouth", "Clean metal outside, severe loss inside", "Often under seals or fasteners"],
        "fractography": {"macro": "Localised loss confined to the crevice geometry", "micro": "Etched, sometimes pitted, crevice surface"},
        "astm": ["G48 crevice test", "G78 crevice corrosion of stainless in seawater"],
        "tests": ["Disassemble and inspect joints", "Identify crevice geometry and chemistry", "Alloy crevice resistance"],
        "prevent": ["Design out crevices, use full-penetration welds not lap joints", "Higher-alloy material", "Seal or avoid stagnant gaps"],
    },
    "intergranular_corrosion": {
        "name": "Intergranular corrosion",
        "summary": "Preferential attack along grain boundaries, classically in sensitised stainless steel where chromium carbides starve the boundaries of chromium.",
        "conditions": ["Sensitised stainless (slow cooling or welding, 450 to 850 C)", "Corrosive environment", "Susceptible alloy or heat-affected zone"],
        "evidence": ["Attack following grain boundaries", "Often beside welds (weld decay)", "Grains can drop out, sugaring"],
        "fractography": {"macro": "Roughened, sometimes crumbling, surface near welds", "micro": "Grain-boundary ditching under the microscope"},
        "astm": ["A262 detecting susceptibility to intergranular attack in stainless", "G28 for nickel-rich alloys"],
        "tests": ["Metallography for grain-boundary attack", "Check thermal history and welding", "Sensitisation test"],
        "prevent": ["Use low-carbon (L grade) or stabilised stainless (Ti, Nb)", "Solution anneal after welding", "Control heat input"],
    },
    "galvanic_corrosion": {
        "name": "Galvanic corrosion",
        "summary": "When two dissimilar metals are electrically coupled in an electrolyte, the less noble metal corrodes faster, the more noble one is protected.",
        "conditions": ["Two dissimilar metals in contact", "A connecting electrolyte (water, salt)", "An unfavourable area ratio (small anode)"],
        "evidence": ["Accelerated attack at the joint of the less noble metal", "Clean noble metal", "Worst where wet and where anode is small"],
        "fractography": {"macro": "Preferential loss on one metal at the junction", "micro": "General dissolution morphology"},
        "astm": ["G71 galvanic corrosion testing", "G82 galvanic series for predicting behaviour"],
        "tests": ["Identify the metals and the couple", "Check the galvanic series and area ratio", "Confirm the electrolyte"],
        "prevent": ["Insulate dissimilar metals, break the circuit", "Pick metals close in the galvanic series", "Favourable area ratio, coat the cathode"],
    },
    "stress_corrosion_cracking": {
        "name": "Stress corrosion cracking (SCC)",
        "summary": "Cracking from the combination of sustained tensile stress, a specific corrosive environment, and a susceptible alloy, even when each factor alone is harmless.",
        "conditions": ["Sustained tensile stress (applied or residual)", "A specific environment (chlorides for austenitic stainless, ammonia for brass)", "A susceptible alloy"],
        "evidence": ["Fine, often branched cracks", "Little visible corrosion or deformation", "Develops over time under steady stress"],
        "fractography": {"macro": "Branched cracks, brittle look despite a ductile alloy", "micro": "Transgranular or intergranular cracking, sometimes mud-cracked oxide"},
        "astm": ["G36 boiling MgCl2 test", "G30 U-bend specimens", "G38 C-ring", "G129 slow strain rate testing"],
        "tests": ["Identify the environment (chlorides, ammonia, caustic)", "Measure residual stress", "Metallography of the crack path", "Confirm alloy susceptibility"],
        "prevent": ["Remove the specific environment or the residual stress (stress relief)", "Change to a resistant alloy", "Coatings or cathodic protection"],
    },
    "corrosion_fatigue": {
        "name": "Corrosion fatigue",
        "summary": "Cyclic loading in a corrosive environment, which lowers fatigue strength and removes the usual fatigue limit, so cracks grow faster than in air.",
        "conditions": ["Cyclic load plus a corrosive environment", "No safe fatigue limit", "Often marine, humid, or chemical service"],
        "evidence": ["Fatigue-like cracking with corrosion in the crack", "Multiple initiation sites and pits", "Faster growth than dry fatigue"],
        "fractography": {"macro": "Beach marks plus corrosion product and pitting at origins", "micro": "Striations partly obscured by corrosion"},
        "astm": ["E466 with environment", "G129 slow strain rate", "F1801 corrosion fatigue of implant metals"],
        "tests": ["Fractography plus chemistry of crack faces", "Identify the environment", "Pit-to-crack transition assessment"],
        "prevent": ["Protect the surface (coatings, inhibitors, cathodic protection)", "Reduce cyclic stress", "More resistant alloy"],
    },
    "hydrogen_embrittlement": {
        "name": "Hydrogen embrittlement",
        "summary": "Loss of ductility and delayed cracking in high-strength steels when atomic hydrogen (from plating, pickling, welding, or service) enters the metal under stress.",
        "conditions": ["High-strength steel (roughly above 1000 MPa)", "A hydrogen source (electroplating, acid pickling, cathodic protection, H2S)", "Sustained tensile stress"],
        "evidence": ["Delayed, sudden brittle cracking after loading", "Little deformation despite a normally ductile steel", "Failure hours to days after assembly"],
        "fractography": {"macro": "Flat brittle fracture, no necking", "micro": "Intergranular (often) or quasi-cleavage, with secondary cracks"},
        "astm": ["F519 hydrogen embrittlement of plating processes", "F1624 incremental step-load test", "G142 hydrogen at high pressure or temperature"],
        "tests": ["Check for a hydrogen source in processing or service", "Strength/hardness level of the steel", "SEM for intergranular fracture"],
        "prevent": ["Bake out hydrogen after plating", "Avoid hydrogen-charging processes for high-strength parts", "Lower the strength level or sustained stress"],
    },
    "creep": {
        "name": "Creep / creep rupture",
        "summary": "Slow, time-dependent deformation under sustained load at high temperature (typically above about 0.4 of the melting temperature), ending in rupture.",
        "conditions": ["High temperature (boilers, turbines, engines)", "Sustained load over long times", "A stress that is safe at room temperature"],
        "evidence": ["Gradual elongation, bulging, or sagging", "Long time to failure", "Often oxidised surfaces"],
        "fractography": {"macro": "Bulging or thinning, oxidised, often multiple cracks", "micro": "Grain-boundary creep cavities and voids, intergranular fracture"},
        "astm": ["E139 creep, creep-rupture, and stress-rupture testing", "E633 temperature measurement guidance"],
        "tests": ["Confirm metal temperature and time at temperature", "Metallography for creep voids", "Compare with creep-rupture data"],
        "prevent": ["Lower the metal temperature or stress", "Use a creep-resistant alloy (superalloy)", "Set and respect a service-life limit"],
    },
    "wear": {
        "name": "Wear (adhesive / abrasive)",
        "summary": "Progressive surface loss from sliding or rolling contact, by adhesion (galling, scuffing) or abrasion by hard particles, changing dimensions and fit.",
        "conditions": ["Sliding or rolling contact", "Inadequate lubrication or hardness", "Hard particles or debris"],
        "evidence": ["Grooves, scoring, galling, or polishing", "Dimensional change at contact surfaces", "Wear debris"],
        "fractography": {"macro": "Scored, galled, or polished contact surfaces", "micro": "Plowing, smearing, or transferred material"},
        "astm": ["G99 pin-on-disk wear", "G65 dry sand / rubber wheel abrasion", "G133 linearly reciprocating wear"],
        "tests": ["Inspect and measure contact surfaces", "Check lubrication and surface hardness", "Identify the abrasive"],
        "prevent": ["Improve lubrication, surface hardness or coatings", "Reduce contact stress and abrasive ingress", "Wear-resistant materials"],
    },
    "erosion": {
        "name": "Erosion (and cavitation)",
        "summary": "Surface loss from impacting fluid, particles, or collapsing vapour bubbles (cavitation), common in pumps, valves, pipe bends and impellers.",
        "conditions": ["High-velocity fluid or particle impingement", "Cavitation (low pressure then bubble collapse)", "Bends, orifices, impellers"],
        "evidence": ["Directional grooves or a polished, wavy surface", "Pitting from cavitation that looks spongy", "Loss on the impingement side"],
        "fractography": {"macro": "Smooth wavy erosion, or spongy cavitation pitting", "micro": "Deformed, fatigued micro-craters for cavitation"},
        "astm": ["G73 liquid impingement erosion", "G32 cavitation erosion (vibratory)", "G76 solid particle erosion"],
        "tests": ["Map loss vs flow direction", "Check velocities and pressures (cavitation)", "Identify entrained particles"],
        "prevent": ["Reduce velocity and turbulence, redesign flow path", "Harder or more erosion-resistant materials", "Raise suction pressure to stop cavitation"],
    },
    "fretting": {
        "name": "Fretting (and fretting fatigue)",
        "summary": "Damage at clamped or press-fit joints with tiny oscillatory micro-movement, producing oxide debris and surface pits that can seed fatigue cracks.",
        "conditions": ["Clamped or interference joints with micro-slip", "Vibration", "Bolted flanges, splines, bearing fits, dovetails"],
        "evidence": ["Reddish-brown oxide debris (cocoa) on steel", "Local pitting and surface damage at contact edges", "Fatigue cracks starting at the fretted zone"],
        "fractography": {"macro": "Fretting scars and oxide debris, cracks at the contact edge", "micro": "Fatigue striations from the fretted origin"},
        "astm": ["E466 / E647 for the resulting fatigue", "ASM Handbook Vol 11 fretting guidance"],
        "tests": ["Inspect the contact interface for debris and pits", "Confirm vibration and micro-slip", "Map crack origin to the fretted zone"],
        "prevent": ["Increase clamping to stop slip, or lubricate to allow it", "Surface treatments (coatings, shot peen)", "Reduce vibration"],
    },
    "thermal_fatigue": {
        "name": "Thermal fatigue",
        "summary": "Cracking from repeated heating and cooling, where constrained thermal expansion creates cyclic stress, common in moulds, exhausts, turbine parts and brakes.",
        "conditions": ["Repeated thermal cycling", "Constraint that prevents free expansion", "Steep temperature gradients"],
        "evidence": ["Networks of cracks (craze or crazing pattern)", "Cracks at hot spots and edges", "Oxidised crack faces"],
        "fractography": {"macro": "Crazed crack network (crocodile skin), oxidised", "micro": "Oxidised intergranular or transgranular cracks"},
        "astm": ["E2368 strain-controlled thermomechanical fatigue", "E606 strain-controlled fatigue (isothermal)"],
        "tests": ["Map cracks vs thermal gradient", "Confirm cycle count and temperature swing", "Check constraint and coatings"],
        "prevent": ["Reduce thermal gradients and constraint", "Use thermal-shock-resistant materials or coatings", "Round edges and hot spots"],
    },
}

# ---------------------------------------------------------------------------
# Material reference (rough screening ranges, not design data).
# ---------------------------------------------------------------------------
MATERIALS = {
    "mild steel": {"class": "bcc_steel", "uts_mpa": "400 to 550", "notes": "Ductile at room temperature but has a ductile-to-brittle transition; rusts readily.", "watch": ["brittle_fracture", "fatigue", "general_corrosion"]},
    "structural steel": {"class": "bcc_steel", "uts_mpa": "400 to 550", "notes": "BCC steel; tough above its transition temperature, brittle below it.", "watch": ["brittle_fracture", "fatigue", "general_corrosion"]},
    "hsla steel": {"class": "bcc_steel", "uts_mpa": "450 to 700", "notes": "High-strength low-alloy steel; better strength and toughness than plain carbon.", "watch": ["fatigue", "brittle_fracture"]},
    "medium carbon steel": {"class": "bcc_steel", "uts_mpa": "600 to 850", "notes": "Quench-and-temper steel for shafts and gears.", "watch": ["fatigue", "brittle_fracture", "wear"]},
    "4140 alloy steel": {"class": "high_strength_steel", "uts_mpa": "900 to 1300", "notes": "Chromoly; strong and tough when tempered, notch sensitive when hard.", "watch": ["fatigue", "hydrogen_embrittlement", "brittle_fracture"]},
    "4340 alloy steel": {"class": "high_strength_steel", "uts_mpa": "1100 to 1800", "notes": "Aircraft-grade high strength; prone to hydrogen embrittlement at high hardness.", "watch": ["hydrogen_embrittlement", "fatigue", "brittle_fracture"]},
    "high-strength steel": {"class": "high_strength_steel", "uts_mpa": "1000 to 2000", "notes": "Strong but notch-sensitive and prone to hydrogen embrittlement.", "watch": ["hydrogen_embrittlement", "brittle_fracture", "fatigue"]},
    "spring steel": {"class": "high_strength_steel", "uts_mpa": "1300 to 1900", "notes": "High hardness for springs; very fatigue and HE sensitive.", "watch": ["fatigue", "hydrogen_embrittlement"]},
    "tool steel": {"class": "high_strength_steel", "uts_mpa": "1500 to 2200", "notes": "Very hard, low toughness; chips and cracks under impact.", "watch": ["brittle_fracture", "wear", "fatigue"]},
    "grey cast iron": {"class": "cast_iron", "uts_mpa": "150 to 400", "notes": "Brittle graphite flakes; good in compression, damping and wear, poor in tension.", "watch": ["brittle_fracture", "wear"]},
    "ductile iron": {"class": "cast_iron", "uts_mpa": "400 to 700", "notes": "Nodular graphite gives more ductility than grey iron.", "watch": ["fatigue", "brittle_fracture"]},
    "304 stainless": {"class": "stainless", "uts_mpa": "500 to 700", "notes": "Austenitic; tough and corrosion resistant but susceptible to chloride SCC and sensitisation.", "watch": ["stress_corrosion_cracking", "pitting_corrosion", "intergranular_corrosion"]},
    "316 stainless": {"class": "stainless", "uts_mpa": "500 to 700", "notes": "Added Mo improves pitting and chloride resistance, still SCC-prone in hot chlorides.", "watch": ["stress_corrosion_cracking", "pitting_corrosion", "crevice_corrosion"]},
    "304l / 316l stainless": {"class": "stainless", "uts_mpa": "480 to 680", "notes": "Low carbon to resist sensitisation and weld decay.", "watch": ["pitting_corrosion", "stress_corrosion_cracking"]},
    "410 stainless": {"class": "stainless", "uts_mpa": "450 to 700", "notes": "Martensitic, magnetic, harder but less corrosion resistant; can embrittle.", "watch": ["brittle_fracture", "pitting_corrosion", "hydrogen_embrittlement"]},
    "17-4 ph stainless": {"class": "stainless", "uts_mpa": "900 to 1300", "notes": "Precipitation-hardening, high strength; watch SCC and HE in some conditions.", "watch": ["stress_corrosion_cracking", "hydrogen_embrittlement", "fatigue"]},
    "2205 duplex stainless": {"class": "stainless", "uts_mpa": "650 to 900", "notes": "Duplex; strong with good chloride SCC resistance.", "watch": ["pitting_corrosion", "fatigue"]},
    "aluminium 6061": {"class": "aluminium", "uts_mpa": "250 to 310", "notes": "Light, weldable, no clear fatigue limit; moderate corrosion resistance.", "watch": ["fatigue", "corrosion_fatigue", "pitting_corrosion"]},
    "aluminium 2024": {"class": "aluminium", "uts_mpa": "400 to 480", "notes": "High strength aircraft alloy, relatively poor corrosion resistance.", "watch": ["fatigue", "stress_corrosion_cracking", "pitting_corrosion"]},
    "aluminium 7075": {"class": "aluminium", "uts_mpa": "500 to 570", "notes": "Very high strength; notably SCC-susceptible in the peak-aged T6 temper.", "watch": ["stress_corrosion_cracking", "fatigue", "pitting_corrosion"]},
    "cast aluminium a356": {"class": "aluminium", "uts_mpa": "230 to 310", "notes": "Common casting alloy; porosity can seed fatigue.", "watch": ["fatigue", "pitting_corrosion"]},
    "titanium cp": {"class": "titanium", "uts_mpa": "240 to 550", "notes": "Commercially pure; excellent corrosion resistance, lower strength.", "watch": ["fatigue", "fretting"]},
    "titanium ti-6al-4v": {"class": "titanium", "uts_mpa": "900 to 1000", "notes": "Strong, light, corrosion resistant; watch fatigue, fretting and hot-salt effects.", "watch": ["fatigue", "fretting"]},
    "inconel 718": {"class": "superalloy", "uts_mpa": "1200 to 1400", "notes": "Nickel superalloy for high temperature; creep and fatigue limited.", "watch": ["creep", "fatigue", "thermal_fatigue"]},
    "inconel 625": {"class": "superalloy", "uts_mpa": "800 to 1000", "notes": "Corrosion and high-temperature resistant nickel alloy.", "watch": ["creep", "thermal_fatigue"]},
    "nickel superalloy": {"class": "superalloy", "uts_mpa": "1000 to 1300", "notes": "Turbine alloys; creep and oxidation are the limits.", "watch": ["creep", "thermal_fatigue", "fatigue"]},
    "brass": {"class": "copper_alloy", "uts_mpa": "300 to 550", "notes": "Copper-zinc; classic ammonia SCC (season cracking) and dezincification.", "watch": ["stress_corrosion_cracking", "general_corrosion", "erosion"]},
    "bronze": {"class": "copper_alloy", "uts_mpa": "300 to 650", "notes": "Copper-tin; good bearing and corrosion behaviour.", "watch": ["wear", "fatigue", "erosion"]},
    "copper": {"class": "copper_alloy", "uts_mpa": "200 to 360", "notes": "Ductile, corrosion resistant in many environments, soft so wears and erodes.", "watch": ["erosion", "wear", "fatigue"]},
    "cupronickel": {"class": "copper_alloy", "uts_mpa": "350 to 500", "notes": "Seawater piping alloy, good erosion-corrosion resistance.", "watch": ["erosion", "pitting_corrosion"]},
    "magnesium az31": {"class": "magnesium", "uts_mpa": "200 to 290", "notes": "Very light, low strength, poor corrosion and galvanic behaviour.", "watch": ["galvanic_corrosion", "fatigue", "general_corrosion"]},
    "zinc / galvanised": {"class": "zinc", "uts_mpa": "100 to 300", "notes": "Sacrificial coating metal; corrodes to protect steel.", "watch": ["general_corrosion", "galvanic_corrosion"]},
    "solder (sn-pb / sn-ag)": {"class": "solder", "uts_mpa": "30 to 60", "notes": "Low melting joint metal; creeps and thermally fatigues in electronics.", "watch": ["thermal_fatigue", "creep", "fatigue"]},
}
